"""initial schema

Revision ID: a8d482b9ceac
Revises: 
Create Date: 2026-09-05 04:09:48.130896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d482b9ceac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=False),
    sa.Column('enriched_context', sa.JSON(), nullable=False),
    sa.Column('judgment', sa.JSON(), nullable=True),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('approvals', sa.JSON(), nullable=False),
    sa.Column('execution_log', sa.JSON(), nullable=False),
    sa.Column('evidence_pack_id', sa.String(length=64), nullable=True),
    sa.Column('autonomy_level_default', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tttr_seconds', sa.Integer(), nullable=True),
    sa.Column('agg_key', sa.String(length=32), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_agg_key'), ['agg_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('proactive_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('cases_created', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('proactive_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proactive_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_proactive_runs_started_at'), ['started_at'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('approver_role', sa.String(length=32), nullable=False),
    sa.Column('approver_user', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_records_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_records_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_records_ts'), ['ts'], unique=False)

    op.create_table('evidence_packs',
    sa.Column('pack_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('process_tree', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('llm_reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('iocs', sa.JSON(), nullable=False),
    sa.Column('mitre_mapping', sa.JSON(), nullable=False),
    sa.Column('compliance', sa.JSON(), nullable=False),
    sa.Column('escalation', sa.JSON(), nullable=False),
    sa.Column('ir_decision', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('pack_id')
    )
    with op.batch_alter_table('evidence_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_packs_case_id'), ['case_id'], unique=False)

    op.create_table('playbook_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=False),
    sa.Column('iocs_collected', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbook_runs_playbook_id'), ['playbook_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_username'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbook_runs_playbook_id'))

    op.drop_table('playbook_runs')
    with op.batch_alter_table('evidence_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_packs_case_id'))

    op.drop_table('evidence_packs')
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_records_ts'))
        batch_op.drop_index(batch_op.f('ix_approval_records_case_id'))
        batch_op.drop_index(batch_op.f('ix_approval_records_action_id'))

    op.drop_table('approval_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('proactive_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proactive_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_proactive_runs_agent_name'))

    op.drop_table('proactive_runs')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_cases_agg_key'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
